### ISSUE TITLE
Using this got file renamed.

### ISSUE THREAD

**Issue by sunshineo** [antonagestam/collectfast#10]
I'm using heroku and django-storage
so say I modified myclass.css, push to heroku, run collectstatics
I would get a myclass_1.css on s3

Please help!

**Comment by browniebroke** [comment]
To separate behaviour for static and media files we use 2 tiny subclasses of Django storage. We can then customise the option for one and not the other.

I've explained it a little bit more in [that issue](https://github.com/jschneier/django-storages/issues/56). For me, that's a Django-storages issue, not one with collectfast.

**Comment by antonagestam** [comment]
Thanks @browniebroke, closing this issue for now.
