### ISSUE TITLE
use public API please

### ISSUE THREAD

**Issue by nschlemm** [antonagestam/collectfast#101]
trying out collectfast with [django-minio-storage](https://pypi.python.org/pypi/django-minio-storage), I stumbled over [collectfast.etag.get_remote_etag()](https://github.com/jazzband/collectfast/blob/master/collectfast/etag.py#L38-L39) causing an
`AttributeError: 'MinioStaticStorage' object has no attribute '_normalize_name'`
which can easily be replaced by the public [storages.utils.safe_join()](https://github.com/jschneier/django-storages/blob/master/storages/utils.py#L48) which is called by [storages.backends.s3boto3.S3Boto3Storage._normalize_name()](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto3.py#L375)

**Comment by antonagestam** [comment]
For reference, my ambitions has been for Collectfast to be usable for other storage engines as well, just never used anything else than S3 personally. Would be cool to introduce a concept of different strategies for different backends.

Moving away from private APIs is a great start :)
