### ISSUE TITLE
Memcached errors

### ISSUE THREAD

**Issue by mheppner** [antonagestam/collectfast#103]
I apologize in advance if this isn't an issue directly related to this library, but I can't figure out what's going on. I'm testing this out on FreeBSD 11 with memcached as a backend:

```
python36-3.6.1_4
libmemcached-1.0.18_6
memcached-1.4.34_2
```
```
boto==2.47.0
Collectfast==0.5.2
Django==1.11.2
django-storages==1.5.2
pylibmc==1.5.2
```

I have `collectfast` listed before `django.contrib.staticfiles` in `INSTALLED_APPS`, a dedicated `COLLECTFAST_CACHE` setup using pylibmc, and `COLLECTFAST_THREADS` set anywhere from 2 to 20. memcached is started with flags `-m 1024 -I 128m`.

Using `collectstatic --disable-collectfast`, the static files are copied to the S3 bucket without any problems. When I try it with collectfast enabled, I get all sorts of memcached errors:

- error 21 from memcached_set
- error 9 from memcached_set: (0x80e83d000) bad command line format,  host: 127.0.0.1:11211
- error 11 from memcached_set
- error 31 from memcached_get(fastcache_:1:collectfast05_asset): (0x80ea3d000) A TIMEOUT OCCURRED,  host: 127.0.0.1:11211 -> libmemcached/get.cc:314

The odd thing is that I have other things in Django using memcached, connecting to the same server. In the shell, I can get/set from either the default cache or the dedicated collectfast cache perfectly fine. 

I've printed out the calls in `etags.py` to see the keys and etags being set, and I can manually set them to memcached in a Python shell without any problems. This only happens when running `collectstatic`. When `collectstatic` finishes running, Python itself ends in a seg fault.

I switched to using a file-base cache and haven't seen any errors. Any ideas of what's happening?

**Comment by antonagestam** [comment]
Do you see the same behavior with `COLLECTFAST_THREADS = False`?

**Comment by mheppner** [comment]
Sorry for the delay. With `COLLECTFAST_THREADS = False`, the errors do not appear.

Running `echo "stats settings" | nc 127.0.0.1 11211` shows that the default of `maxconns 1024` is set. The total connections is 38 when not running `manage.py collectstatic`, so there's no way I'm hitting the connections limit.

**Comment by antonagestam** [comment]
Yeah, this incompatibility should probably be documented.

**Comment by antonagestam** [comment]
Documentation already mentions "a dedicated cache backend must be setup and it must use a backend that is threadsafe"
