### ISSUE TITLE
Threading incompatible with HashedFilesMixin

### ISSUE THREAD

**Issue by smcoll** [antonagestam/collectfast#107]
For an S3 storage class using the `HashedFilesMixin` (e.g. `CachedFilesMixin` or `ManifestFilesMixin`), a `ValueError` will be raised when `collectstatic` is run with an empty S3 bucket (or more precisely, a bucket lacking any one of the original static files):

```
ValueError: The file 'mypath/myfont.eot' could not be found with <myapp.MyStorageClass object at 0x7fa786804978>.
```

This only occurs when `COLLECTFAST_THREADS` is not `False`.  When the `HashedFilesMixin.hashed_name`  method uses `exists()` to determine whether the file for the cleaned file name exists (on S3), a `ValueError` is raised, since it doesn't.  i assume this is due to a race condition.

At first i thought that overriding `hashed_name` to compute based on file contents of local static media would fix that issue (and be faster?), but for third-party apps, that raises a `SuspiciousFileOperation`.

**Comment by antonagestam** [comment]
What is the usecase for this? Collectfast already provides hashing of the contents of the files.

I remember reading up on HashedFilesMixins and its siblings when they were released to see if it was something that Collectfast could utilize but I decided then that they did not really add value and weren't what I thought they was initially.

Now I can't find documentation for them making it a hard (or even bad?) thing to support.

I also think that generally, it's not a good idea for Collectfast to work around this. It has to be up the developer to provide a storage that is threadsafe, or not use the multithreading feature.

What are your thoughts?

**Comment by smcoll** [comment]
The base `HashedFilesMixin` class is not documented, but two implementations are: [ManifestFilesMixin](https://docs.djangoproject.com/en/1.11/ref/contrib/staticfiles/#manifeststaticfilesstorage) and [CachedFilesMixin](https://docs.djangoproject.com/en/1.11/ref/contrib/staticfiles/#cachedstaticfilesstorage).

`ManifestFilesMixin` uses hashes for browser cache busting:
> The purpose of this storage is to keep serving the old files in case some pages still refer to those files, e.g. because they are cached by you or a 3rd party proxy server. Additionally, it’s very helpful if you want to apply far future Expires headers to the deployed files to speed up the load time for subsequent page visits.

In my case, i am storing files in S3 and using `ManifestFilesMixin` for browser cache busting.  You might be right that a fix could be out of scope, but given that this package explicitly supports S3 as a storage backend, and that `ManifestFilesMixin` is a stock Django storage mixin, i think this is a good candidate for resolution.

**Comment by antonagestam** [comment]
@smcoll The issue here in my opinion is that HashedFilesMixin isn't thread safe. I believe very few parts of Django are thread safe. Yes, this package explicitly supports S3, but it doesn't explicitly support every storage backend.

Using multithreading will always be incompatible with storage backends that aren't thread safe, we can't change that. So the only solution would be to implement new `ManifestFilesMixin` and `CachedFilesMixin` classes that are thread safe. This thread safety would be useful in your usecase but wouldn't be unique to Collectfast and therefore can live in a separate repository or even in Django.
