### ISSUE TITLE
Need feasibility with google cloud platform

### ISSUE THREAD

**Issue by snig-b** [antonagestam/collectfast#122]
I have used this library before with one of my S3 projects.
Recently we have moved a project to GCP storage. Collectstatic from a regular server is excruciatingly slow.
I need the benefits of this library for a GCP backend as well. 
Can I expect any such changes in the near future?

**Comment by antonagestam** [comment]
@snig-b No one is working on that as far as I know. If you feel like implementing it, I'd be happy to review pull requests.

**Comment by antonagestam** [comment]
@snig-b btw, did you run into any specific problems using collectfast?

**Comment by jpnauta** [comment]
Fixed this in #137

**Comment by antonagestam** [comment]
1.2.0 is now on PyPI
