### ISSUE TITLE
reported version?

### ISSUE THREAD

**Issue by tisdall** [antonagestam/collectfast#130]
I messed up and accidentally had the INSTALLED_APPS order wrong.  When I was trying to determine which `collectstatic` was working I tried using `python manage.py collectstatic --version`.  However, even after I fixed the issue it was still reporting my Django version instead of the version of Collectfast.

Yes, it's a really small and pedantic thing, but `--version` should be reporting the version of Collectfast.

**Comment by antonagestam** [comment]
I'll happily review a pull request for this.

**Comment by antonagestam** [comment]
The implementation should probably override `BaseCommand.get_version()` and make it return something like `"collectfast version: <version>"`.

https://docs.djangoproject.com/en/2.1/howto/custom-management-commands/#django.core.management.BaseCommand.get_version
