### ISSUE TITLE
sdist tests not runnable

### ISSUE THREAD

**Issue by jayvdb** [antonagestam/collectfast#131]
The source distribution isnt testable as-is.

Ideally one of the following should work.
```sh
python setup.py test
python `which django-admin` test
```

I see this project uses `tox` and `runtests.py`.

The files to support that are not included in the sdist.

**Comment by antonagestam** [comment]
I'll happily review pull requests for this.

**Comment by jayvdb** [comment]
I'll be happy to help with the packaging, but currently that isnt helpful as https://github.com/antonagestam/collectfast/issues/132 means all is broken for me, so fixing packaging isnt useful.

**Comment by antonagestam** [comment]
Agreed. I probably won't find the time to fix it for at least a few weeks though.

**Comment by antonagestam** [comment]
This should now be more feasible to implement as [tests that require a working backend are marked and skipped when `SKIP_LIVE_TESTS=true` is set](https://github.com/antonagestam/collectfast/commit/1dc571c0d8181870fc0e0531dd705e2c3121e2bd).

However, I noticed `python setup.py test` [is now deprecated](https://github.com/pypa/setuptools/issues/1684) (noticed your comments in the discussion too). Do you have any opinions on on the issue or guidance on how and if we should strive to achieve a testable source distribution?

**Comment by antonagestam** [comment]
Closing this for now, feel to re-open if there's interest for this.

**Comment by jayvdb** [comment]
Distros still test from source distributions, using `setup.py test` by default.  Nothing has changed there - deprecation notices had zero effect.  When they actually break it, there are several setuptools plugins which provide the `test` command, and distros will start using one of those.
