### ISSUE TITLE
Postprocess fails because upload happens after collect command.

### ISSUE THREAD

**Issue by justinwang189** [antonagestam/collectfast#133]
Running into error during post-processing 
```
django/contrib/staticfiles/storage.py", line 101, in hashed_name:    
raise ValueError("The file '%s' could not be found with %r." % (filename, self))
```

I believe this happens because the underlying collect() command also runs post-process. But because this library overrides collects such that uploads don't happen until the underlying collection function completes. The image has not actually been uploaded yet.

Happy to submit PR to delay the post-process function

**Comment by antonagestam** [comment]
Sorry for the late response. I'll be happy to review your PR.

**Comment by bblanchon** [comment]
I have a similar error:

```
Post-processing 'admin/css/widgets.css' failed!

  Traceback (most recent call last):
  File "manage.py", line 16, in <module>
  execute_from_command_line(sys.argv)
  File "django/core/management/__init__.py", line 381, in execute_from_command_line
  utility.execute()
  File "django/core/management/__init__.py", line 375, in execute
  self.fetch_command(subcommand).run_from_argv(self.argv)
  File "django/core/management/base.py", line 323, in run_from_argv
  self.execute(*args, **cmd_options)
  File "django/core/management/base.py", line 364, in execute
  output = self.handle(*args, **options)
  File "collectfast/management/commands/collectstatic.py", line 81, in handle
  super(Command, self).handle(**options)
  File "django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
  collected = self.collect()
  File "collectfast/management/commands/collectstatic.py", line 72, in collect
  ret = super(Command, self).collect()
  File "django/contrib/staticfiles/management/commands/collectstatic.py", line 134, in collect
  raise processed
  File "django/contrib/staticfiles/storage.py", line 294, in _post_process
  content = pattern.sub(converter, content)
  File "django/contrib/staticfiles/storage.py", line 195, in converter
  force=True, hashed_files=hashed_files,
  File "django/contrib/staticfiles/storage.py", line 132, in _url
  hashed_name = hashed_name_func(*args)
  File "django/contrib/staticfiles/storage.py", line 343, in _stored_name
  cache_name = self.clean_name(self.hashed_name(name))
  File "django/contrib/staticfiles/storage.py", line 93, in hashed_name
  raise ValueError("The file '%s' could not be found with %r." % (filename, self))
  ValueError: The file 'admin/img/selector-icons.svg' could not be found with <myproject.storage_backends.S3StaticStorage object at 0x7f8bfcc7df60>.
   (ElasticBeanstalk::ExternalInvocationError)
```

My storage class is declared like that:

```python
class S3StaticStorage(ManifestFilesMixin, S3Boto3Storage):
    location = getattr(settings, 'AWS_STATIC_LOCATION', 'static')
    default_acl = 'public-read'
    querystring_auth = False
    preload_metadata = True
    object_parameters = {
        'CacheControl': 'max-age=31556926'  # one year
    }
```

Is there a workaround?

**Comment by justinwang189** [comment]
Sorry, i never ended up finding a good fix for it. And just disabled the collectfast in the meantime

**Comment by arthurio** [comment]
I think you can take the same approach as https://github.com/dreipol/django-collectfaster/blob/master/collectfaster/management/commands/collectstatic.py and hijack the django command's behavior by setting `self.post_process` to `False` and copy/paste the content of the if block [`if self.post_process and hasattr(self.storage, 'post_process'):`](https://github.com/django/django/blob/stable/3.0.x/django/contrib/staticfiles/management/commands/collectstatic.py#L124) to another function like `post_processor` that would be executed after having processed the upload tasks.

**Comment by antonagestam** [comment]
Thanks for reporting and suggesting ways to fix this. 2.1.0 is now published on PyPI with support for `post_process()`. I followed the advice by @arthurio above.

Please test it out and report back if you run into any issues.

**Comment by arthurio** [comment]
Thanks @antonagestam for taking the time to implement the fix, I look forward to trying it out 👍

**Comment by hirenAubergine** [comment]
Thanks @antonagestam for this fix. But I am still facing exact same problem with version 2.2.0

**Comment by antonagestam** [comment]
@hirenAubergine Huh, that's quite sad to hear so long after this was implemented. The reality is that it's quite likely that I will not be able to put in the time required to investigate or fix this. I think it would be helpful if you could post a bug report with a traceback, versions of Django, collectfastl, django-storages and Python as well as as much of the related settings that you can.

If you or anyone else are able to spend time on fixing this, I'd be happy to discuss, review PRs and publish a patch release.
