### ISSUE TITLE
Django 2.1 & 2.2 compatibility?

### ISSUE THREAD

**Issue by jhancia** [antonagestam/collectfast#135]
Is this package compatible with Django 2.1 & 2.2? Anyone using it in production? If so, we should add these versions to tox.ini and travis.yml

**Comment by antonagestam** [comment]
The intention is to support these versions, but I haven't been able to test with them since #132 is sort of blocking. I need to fix the test suite before anything else.

For what it's worth I'm not aware of anything breaking compatibility in those versions and have not seen any bug reports.

**Comment by antonagestam** [comment]
Closed by #141
