### ISSUE TITLE
Python 2 support gone

### ISSUE THREAD

**Issue by jordotech** [antonagestam/collectfast#148]
Hello, 
looks like python 2 support has been lost for 1.0.0 as of [this commit](https://github.com/antonagestam/collectfast/commit/e092439de10442f4d2ba5976dfff99b269177247)

```
collectfast/etag.py", line 5
ImportError: cannot import name lru_cache
```
For this release to work with python 2 one has to `pip install backports.functools_lru_cache` and replace that line with

```
try:
    from functools import lru_cache
except ImportError:
    from backports.functools_lru_cache import lru_cache
```
as described here: https://pypi.org/project/backports.functools_lru_cache/

We need to either update the README.md to show only python3 is supported or revert this change

**Comment by antonagestam** [comment]
Python 2 [will be a dead language in 4 months](https://pythonclock.org/), it will be [supported by Django for a little longer](https://www.djangoproject.com/download/#supported-versions) than that but I don't intend to maintain support for it. This is already specified by classifiers in setup.py.

If you need Python 2 support you'd need to install collectfast<1. I don't anticipate there to be a great demand for this, but if you feel like the readme should be updated I'll review your pull requests.

**Comment by antonagestam** [comment]
I'll close this for now, but feel free to reopen or submit a PR.
