### ISSUE TITLE
Release 1.1.0 breaking change using custom STATICFILES_STORAGE

### ISSUE THREAD

**Issue by dannyshaw** [antonagestam/collectfast#151]
The latest release is not fully backwards compatible and broke our build.

It doesn't correctly guess the strategy to use based on the storage when a custom storage is in place. We're using a subclass of `storages.backends.s3boto3.S3Boto3Storage`.

I think a way forward could be for `guess_strategy()` to actually check for a base class match of the storage class rather than use string matching on the class name. Thoughts?

https://github.com/antonagestam/collectfast/commit/c6da306069ed97c456d81c67dee6c7f76ad4a878#diff-a61a8c583626d902e08672575e0f6daeR144-R149

We've rolled back and do plan to explicitly specify the strategy, just thought I'd raise the issue as anyone else with a subclassed storage is likely to have a broken build from this minor bump.

**Comment by antonagestam** [comment]
Yes, thanks for the bug report. Subclasses should be supported. I'll try to get a bug fix release out as soon as possible.

**Comment by antonagestam** [comment]
Or if anyone else is interested in working on a fix I'll happily review pull requests.

**Comment by antonagestam** [comment]
1.1.1 is now on PyPI

**Comment by dannyshaw** [comment]
Wow thanks for being so responsive! Nice work.
