### ISSUE TITLE
Breaking behavior 1.0.0 -> 1.3.0 (COLLECTSTATIC_STRATEGY)

### ISSUE THREAD

**Issue by pachewise** [antonagestam/collectfast#159]
Not sure if bug or intentional, but `collectstatic` command will break if you don't define `COLLECTSTATIC_STRATEGY` or `STATICFILES_STORAGE` in your settings file (even if `COLLECTFAST_ENABLED = False`). 

![image](https://user-images.githubusercontent.com/2257119/67443243-dbaf5800-f5b8-11e9-9edd-4c26b2364136.png)

**Comment by antonagestam** [comment]
If I understand you report correctly, the error is that collecfast tries to guess a strategy even though `COLLECTFAST_ENABLED` is set to `False`. That makes sense, there should be a check for that in the command.

This should also be better tested.

**Comment by antonagestam** [comment]
Published 1.3.1 with a fix for this issue. Thanks for the report!
