### ISSUE TITLE
Interfering with django-allauth package

### ISSUE THREAD

**Issue by MrAlexWinkler** [antonagestam/collectfast#171]
Was getting error:
`
Django AllAuth KeyError at /accounts/login/ 'BACKEND'
`

Full documentation of error and temp fix
https://stackoverflow.com/questions/60251793/django-allauth-keyerror-at-accounts-login-backend

**Comment by antonagestam** [comment]
@MrAlexWinkler I'm not seeing the issue here. Can you provide:

1. Expected behavior
2. Actual behavior
3. Stack trace

The information you have provided is not enough to understand the issue.

**Comment by antonagestam** [comment]
Closing until more information is provided.
