### ISSUE TITLE
Threads setting typing

### ISSUE THREAD

**Issue by Schlepptop** [antonagestam/collectfast#178]
The changes to collectfast.settings merged in #173 state that the COLLECTFAST_THREADS setting should be of type bool, while the readme gives an example in which they are of type int, which is also what `multiprocesses.Pool()` expects in https://github.com/antonagestam/collectfast/blob/fc3ebab9e11e857d0068696d9781f167ec911766/collectfast/management/commands/collectstatic.py#L73

**Comment by antonagestam** [comment]
Good find, `settings.threads` should indeed be `int` and its default should be `0` instead of `False`. I should have probably added a few test cases with valid settings as well. If you'd feel like fixing this I'd be happy to review PRs, otherwise I'll try to get to it sometime this week.

**Comment by antonagestam** [comment]
2.0.1 is now released with the fix. Thanks for contributing! 🍰

**Comment by Schlepptop** [comment]
Happy to help :)
