### ISSUE TITLE
Usage guide with Whitenoise library

### ISSUE THREAD

**Issue by viperfx** [antonagestam/collectfast#189]
Hi, 

Since whitenoise needs a middleware set and `STATICFILES_STORAGE` set to `whitenoise.storage.CompressedManifestStaticFilesStorage`

How can we use this library with Whitenoise?

**Comment by antonagestam** [comment]
Could you be more specific about what's not working? What does the rest of your config look like? Are you running into an error?

**Comment by thenewguy** [comment]
@viperfx It should work when you set your strategy to filesystemstrategy.  Please respond back with any errors you encounter.  There is a CachedFilesystemStrategy in the works as well

**Comment by antonagestam** [comment]
Closing due to silence.
