### ISSUE TITLE
Doesn't work for gzipped items

### ISSUE THREAD

**Issue by manterfield** [antonagestam/collectfast#46]
If AWS_IS_GZIPPED is set to True, then this will check the hash of the un-gzipped item against the etag of the gzipped item, which will obviously not match (though once upon a time it used to, but amazon fixed that).

This means all js and css files on a set-up using gzipping will be copied on every collect.

**Comment by lakshbhasin** [comment]
I was wondering if there have been any updates on this, or if anyone has worked on a PR to fix it? I've been encountering the same issue.

**Comment by antonagestam** [comment]
Not as far as I know, feel free to dive in!
Den 30 dec 2015 6:14 em skrev "Laksh Bhasin" <notifications@github.com>:
