### ISSUE TITLE
the default MAX_ENTRIES cache setting (300) is probably worth mentioning in the README

### ISSUE THREAD

**Issue by nebstrebor** [antonagestam/collectfast#47]
I realize its not a collectfast problem, but I spent a long time trying to figure out why caching was only working for a (seemingly random) portion of my static files.  Eventually I found the MAX_ENTRIES default setting for Django caches, which is set to 300 by default (I think this only applies to DB or File Based caching, which is what i'm using for my CollectFast cache).

It may be useful for some users to call out the bad default on the "MAX_ENTRIES" option  when you call out "TIMEOUT" in the README, since they probably won't be familiar with it and it will almost always reduce the effectiveness of CollectFast if used with affected cache types, since only 300 file hashes will be cached

**Comment by browniebroke** [comment]
Created a pull request as I have the issue, and I would have missed it if not checking the issues section.
