### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by TigerDX** [antonagestam/collectfast#62]
Collectfast only ever makes a single cache entry on Windows, meaning I can't `collectstatic` from my development machine.

I believe I have traced this to the use of `storage._normalize_name(prefixed_path)`, which returns a Windows style directory structure with double backslashes instead of forward slashes, i.e. it doesn't normalize paths.

I'll see if there's anything I can do to patch it and I'll create a pull request, unless someone come up with a better place to fix it.

**Comment by antonagestam** [comment]
@TigerDX See my comment here: https://github.com/antonagestam/collectfast/pull/45#issuecomment-103683583

**Comment by TigerDX** [comment]
It's a shame if you won't accept any commits to fix this. I had planned on a simple replace of '\\' to '/', but if even that is too much, we can close this issue.

**Comment by antonagestam** [comment]
@TigerDX I'll accept as long as tests are valid and passing. I can't commit to supporting Windows because I have literally no way to run tests there :)

**Comment by TigerDX** [comment]
@antonagestam Of course, and thanks for taking the time to respond. I'll put together a PR with the replacement fix, which shouldn't affect other platforms.
