### ISSUE TITLE
Question: have you proposed this to Django itself?

### ISSUE THREAD

**Issue by flaviamissi** [antonagestam/collectfast#64]
I really like the option of not having to collect statics that haven't changed, I'd love if this became an option to the `collectsatic` command itself.

So I was asking myself if you ever discussed that on `django-dev`?

Thanks for the project!

**Comment by antonagestam** [comment]
Hi @flaviamissi,
I've never discussed this on `django-dev`, feel free to bring it up! :+1: :)

**Comment by antonagestam** [comment]
And if you do, please link to it here!
