### ISSUE TITLE
Python 3 can't install

### ISSUE THREAD

**Issue by shredding** [antonagestam/collectfast#76]
The readme.rst contains non-ascii chars which fails the setup on python 3 if i install it via pip.

It would work if I do open with `encoding='utf-8'`, but that would fail python 2 i assume (I haven't used python 2 since years)?

**Comment by pydolan** [comment]
Installing with python 3.5.1 works for me (pip version 8.1.2). The readme.rst file is outside of the python code, so I'm not sure why it would cause problems for you. Can you elaborate?

**Comment by antonagestam** [comment]
@shredding Thanks for documenting this

@pydolan setup.py opens the readme file to add it as `long_description`.

**Comment by antonagestam** [comment]
@shredding What's the exception you're getting? What system are you on? Tests are running 3.5 since a while back and I can't reproduce this.

**Comment by shredding** [comment]
Hm. I can't verify it any longer as well.

I have tried with a very simple setup:

Dockerfile:
```
FROM python:onbuild
MAINTAINER Christian Peters <chp@digitale-avantgarde.com>
```

requirements.txt:

```
collectfast==0.2.3
```

... and it build without error.

So, hm. But I fail to spot the non-unicode text in the Readme.rst any longer, though I do not see it within the commit log as well.

So, i guess we can close this one?

**Comment by antonagestam** [comment]
@shredding Cool, thanks for the feedback!
