### ISSUE TITLE
AttributeError: 'Bucket' object has no attribute 'Object'

### ISSUE THREAD

**Issue by andy-io** [antonagestam/collectfast#85]
When i try to do an upload of a file to s3 and get its etag, i get this error

```
  File "/venv3/lib/python3.5/site-packages/collectfast/management/commands/collectstatic.py", line 84, in get_boto3_etag
    return self.storage.bucket.Object(path).e_tag
AttributeError: 'Bucket' object has no attribute 'Object'
```

Django = 1.10.1
python = 3.5

**Comment by antonagestam** [comment]
What version of boto do you have installed?

**Comment by andy-io** [comment]
i have the following in my env:
boto==2.42.0
boto3==1.4.3

**Comment by antonagestam** [comment]
Do you have the latest version of Collectfast installed? Some related issues where recently fixed.

**Comment by antonagestam** [comment]
Closing until further information appears

**Comment by python-force** [comment]
It has happened to me today:

boto==2.49.0
boto3 ==1.12.12
collectfast==2.1.0

**Comment by antonagestam** [comment]
@python-force What are the values of the related configuration? It's a bit suspicious that you have both boto and boto3 installed.

**Comment by python-force** [comment]
boto - the last one I am using here: from boto.s3.connection import OrdinaryCallingFormat
AWS_S3_CALLING_FORMAT = OrdinaryCallingFormat()

**Comment by antonagestam** [comment]
@python-force boto [is no longer supported since version 2.0.0](https://github.com/antonagestam/collectfast/blob/master/CHANGELOG.md#200) so you'll have to use boto3 if you want to use Collectfast 2.1.0.

**Comment by antonagestam** [comment]
@python-force Please post the values of `COLLECTFAST_STRATEGY` and `STATICFILES_STORAGE` if you don't think the above is the issue.

**Comment by python-force** [comment]
@antonagestam will play with it and get rid of that 1 boto and see what I am going to get...

In the settings I have:
STATICFILES_STORAGE = 'config.custom_storages.CachedS3BotoStaticStorage'
COLLECTFAST_STRATEGY = "collectfast.strategies.boto3.Boto3Strategy"

**Comment by antonagestam** [comment]
@python-force What are the bases of `config.custom_storages.CachedS3BotoStaticStorage`?

**Comment by python-force** [comment]
from django.conf import settings
from storages.backends.s3boto import S3BotoStorage
from django.core.files.storage import get_storage_class

import os
from django.core.files.storage import FileSystemStorage

# This class is only for migrations - if I remove it migrations won't work
# Has zero functionality
class OverwriteStorage(FileSystemStorage):
    location = settings.MEDIAFILES_LOCATION
    def get_available_name(self, name, max_length=None):
        if self.exists(name):
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        return name

class StaticStorage(S3BotoStorage):
    location = settings.STATICFILES_LOCATION
    file_overwrite = True


class MediaStorage(S3BotoStorage):
    location = settings.MEDIAFILES_LOCATION
    file_overwrite = True


class CachedS3BotoStaticStorage(S3BotoStorage):

    # S3 storage backend that saves the files locally, too.

    location = 'static'

    def __init__(self, *args, **kwargs):
        super(CachedS3BotoStaticStorage, self).__init__(*args, **kwargs)
        self.local_storage = get_storage_class(
            "compressor.storage.CompressorFileStorage")()

    def save(self, name, content):
        name = super(CachedS3BotoStaticStorage, self).save(name, content)
        self.local_storage._save(name, content)
        return name

**Comment by antonagestam** [comment]
Right, so you're using `storages.backends.s3boto.S3BotoStorage` which is no longer supported. You need to either use a previous version of Collectfast such as `1.3.2`, or upgrade to boto3 which you really should do as boto is long deprecated and [no longer supported by django-storages](https://github.com/jschneier/django-storages/blob/master/CHANGELOG.rst#general).

**Comment by python-force** [comment]
Ok thank you, will look into that.
