### ISSUE TITLE
Collectfast 0.5.0 requires Boto3 to be installed

### ISSUE THREAD

**Issue by mjtamlyn** [antonagestam/collectfast#92]
[This commit](https://github.com/antonagestam/collectfast/commit/be5f580f46147bb930e166ce0874fbf1603640b1) adds an import of `S3Boto3Storage` with no fallback, which will fail with "django.core.exceptions.ImproperlyConfigured: Could not load Boto3's S3 bindings." if `boto3` is not installed.

So long as the intention is to continue to support `boto` as well as `boto3`, this import should be conditional.

**Comment by antonagestam** [comment]
Good catch, I'll look into it. Seems like I was sloppy when pushing 0.5 ...

**Comment by antonagestam** [comment]
Or maybe I'll blame it on the storages people for invoking side effects on imports ;)

**Comment by antonagestam** [comment]
@mjtamlyn Would you mind taking a look at https://github.com/antonagestam/collectfast/pull/93 for me?

**Comment by mjtamlyn** [comment]
Looks like that should solve the problem for me :)

**Comment by antonagestam** [comment]
@mjtamlyn Thanks for the help! I just published 0.5.2 on PyPI.
